# Generated by Django 3.1.3 on 2024-09-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20240914_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='testing_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
