# Generated by Django 3.1.3 on 2024-09-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_testing_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='testing_count',
        ),
    ]
